# Generated by Django 4.0.5 on 2022-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120, verbose_name='Name')),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_document', models.CharField(max_length=20, verbose_name='Document')),
                ('employee_phone_number', models.CharField(max_length=20)),
                ('employee_registration_date', models.DateField(auto_now_add=True, verbose_name='Registrtion Date')),
            ],
        ),
    ]
